### ISSUE TITLE
Player does not update current position after once finished

### ISSUE THREAD

**Issue by beautifultown** [beautifultown/Poche#3]
It seems MainActivity's Tick task is not working, from second MainActivity launch.
Strangely, in first MainActivity run the screen updates progresses, but screen does not update once I have exited the screen using back key.

**Comment by jkihgit** [comment]
Reproduced on my device

**Comment by jkihgit** [comment]
Working on this.

Looks like AsyncTask doesn't end when Activity resets, so it keeps trying to update the activity that's already gone.

Trying to reset AsyncTask when Activity goes away / comes back

**Comment by beautifultown** [comment]
How about using Handler.postDelayed() ?
I have used this for detecting double stroke (in BSUI.java). 
I see possibility to use this in updating as well.

**Comment by jkihgit** [comment]
Fixed 5c40b7096091156ec37c04b14082bd59dc367958
