### ISSUE TITLE
BSUI is too sensitive 

### ISSUE THREAD

**Issue by jkihgit** [beautifultown/Poche#4]
Possible enhancements 

Add minimum drag distance to recognize very very short drags as clicks instead 

Add dead zones between angles to prevent inaccurate input. E. G. Ignore +-5 degrees (total of 40 degrees for all 4 directions) every 45 degree interval (e.g. The first is from 40 to 50 degrees) 

Ignore input that starts from the edge of the screen. Prevent accidental input when using bottom buttons or grabbing the device. Bezels are very thin these days.

**Comment by beautifultown** [comment]
In c86e60e3f85a2641972bf0bdec13ff6c13884f39,
Introduced minimum drag distance, dead zones.
Also, instead receiving BSUI events on whole screen, I've added a empty full-sized view with margins.
Please check minimum distance and dead zones and adjust the amount.

**Comment by jkihgit** [comment]
Done, but found a new issue #7 , possibly connected to this.

Edit: Also happens in earlier commits. Just noticing it now.
