### ISSUE TITLE
ParseTouchEvent() takes too long for the initial track

### ISSUE THREAD

**Issue by jkihgit** [beautifultown/Poche#6]
ParseTouchEvent() takes <0.01 sec for other tracks, but starting the initial track takes <0.1 sec, and a notable lag during album art transition is also noticeable.

Optimizing album art transition to use 1/10 screen width resolution images did not help.

No difference is noticeable for music playing (appears to play immediately after swipe).

**Comment by beautifultown** [comment]
I have observed if Poche uses default fallback album art, it takes a lot of time to update UI.
Is the fallback image loading problem related to this issue?

**Comment by beautifultown** [comment]
It seems getAverageColor() takes too long when processing fallback image.
I'm working on caching default colors and restoring them.

**Comment by beautifultown** [comment]
Fixed by not getting average color of fallback album art.
It seems iterating over huge byte array caused performance bottleneck.
Yet, for very initial track, Poche parse the playlist on-the-fly so initial delay is somewhat inevitable unless doing parse in PlaylistActivity.

**Comment by jkihgit** [comment]
Works fine here as well. Closed.
